-- Import geofence data
-- Format: Name; Description; Type; Groups

INSERT INTO public.geofences (name, description, type, groups, metadata) VALUES
('24 Hour Medical Centre (+263776008387)', 'Manyoba Rd, Nketa, Bulawayo, Zimbabwe', 'circle', '', '{"city": "Bulawayo", "country": "Zimbabwe"}'::jsonb),
('A4 Toll Gate', 'Harare-Beitbridge Highway, Beitbridge, Matabeleland South, Zimbabwe, 17.17 km from Beitbridge', 'circle', '', '{"city": "Beitbridge", "province": "Matabeleland South", "country": "Zimbabwe", "distance": "17.17 km from Beitbridge"}'::jsonb),
('AFRICAN TRUCK STOP', 'Pomona Rd, Pomona, Kempton Park 1619, Gauteng, South Africa', 'polygon', '', '{"city": "Kempton Park", "province": "Gauteng", "country": "South Africa", "postal_code": "1619"}'::jsonb),
('Amcotts', 'Anthony Road, Harare, Zimbabwe', 'polygon', '', '{"city": "Harare", "country": "Zimbabwe"}'::jsonb),
('APL LOGISTICS', 'Joshua Nkomo Road, Harare, Zimbabwe', 'polygon', '', '{"city": "Harare", "country": "Zimbabwe"}'::jsonb),
('B Braun Harare', 'Harare Drive, Harare, Zimbabwe', 'polygon', '', '{"city": "Harare", "country": "Zimbabwe"}'::jsonb),
('B Braun Sa', 'Aintree St, Hoogland, Randburg 2194, Gauteng, South Africa', 'polygon', '', '{"city": "Randburg", "province": "Gauteng", "country": "South Africa", "postal_code": "2194"}'::jsonb),
('Baobab Toll Plaza.', 'N1, Musina, Limpopo, South Africa', 'circle', '', '{"city": "Musina", "province": "Limpopo", "country": "South Africa"}'::jsonb),
('BB BORDER ZIM SIDE', 'Harare-Beitbridge Highway, Beitbridge, Matabeleland South, Zimbabwe', 'polygon', '', '{"city": "Beitbridge", "province": "Matabeleland South", "country": "Zimbabwe"}'::jsonb),
('BB TRUCK STOP', 'Harare-Beitbridge Highway, Beitbridge, Matabeleland South, Zimbabwe', 'circle', '', '{"city": "Beitbridge", "province": "Matabeleland South", "country": "Zimbabwe"}'::jsonb),
('Beitbridge hospital (+263 286 22112)', 'Harare-Beitbridge Highway, Beitbridge, Matabeleland South, Zimbabwe', 'circle', '', '{"city": "Beitbridge", "province": "Matabeleland South", "country": "Zimbabwe"}'::jsonb),
('BeitBridge Toll Plaza', 'Bulawayo-Beitbridge Highway, Beitbridge, Matabeleland South, Zimbabwe, 15.54 km from Beitbridge', 'circle', '', '{"city": "Beitbridge", "province": "Matabeleland South", "country": "Zimbabwe", "distance": "15.54 km from Beitbridge"}'::jsonb),
('Birchenough Bridge Hospital', 'Mutare-Masvingo Road, Buhera, Manicaland, Zimbabwe, 0.31 km from Birchenough Bridge', 'circle', '', '{"city": "Buhera", "province": "Manicaland", "country": "Zimbabwe", "distance": "0.31 km from Birchenough Bridge"}'::jsonb),
('BRANDS AFRICA', 'Cranborne Avenue, Harare, Zimbabwe', 'polygon', '', '{"city": "Harare", "country": "Zimbabwe"}'::jsonb),
('Bubi River Truck Stop', 'Harare-Beitbridge Highway, Beitbridge, Matabeleland South, Zimbabwe, Swanscoe', 'circle', '', '{"city": "Swanscoe", "province": "Matabeleland South", "country": "Zimbabwe"}'::jsonb),
('Bulawayo Central Hospital (+263292252111)', 'Haewood Road, Bulawayo, Zimbabwe', 'circle', '', '{"city": "Bulawayo", "country": "Zimbabwe"}'::jsonb),
('BULAWAYO DEPOT', 'Wingrove Road, Bulawayo, Zimbabwe', 'polygon', '', '{"city": "Bulawayo", "country": "Zimbabwe"}'::jsonb),
('BURMA VALLY LOADING POINT', 'Bvumba Road, Mutare, Manicaland, Zimbabwe, 17.65 km from Chitakatira Growth Point', 'polygon', '', '{"city": "Mutare", "province": "Manicaland", "country": "Zimbabwe", "distance": "17.65 km from Chitakatira Growth Point"}'::jsonb),
('BUTLER FARM', 'Delport Road, Harare, Zimbabwe', 'polygon', '', '{"city": "Harare", "country": "Zimbabwe"}'::jsonb),
('Capricorn - Toll Booth', 'N1, Makhado, Limpopo, South Africa', 'circle', '', '{"city": "Makhado", "province": "Limpopo", "country": "South Africa"}'::jsonb),
('CBC', 'Main Street Highway, Chipinge, Manicaland, Zimbabwe, 11.01 km from Chipinge', 'polygon', '', '{"city": "Chipinge", "province": "Manicaland", "country": "Zimbabwe", "distance": "11.01 km from Chipinge"}'::jsonb),
('Checheche St Peter''s Mission Hospital (031 7229)', 'A10, Chipinge, Manicaland, Zimbabwe, 1.54 km from Checheche', 'circle', '', '{"city": "Chipinge", "province": "Manicaland", "country": "Zimbabwe", "distance": "1.54 km from Checheche"}'::jsonb),
('Chegutu Truck Stop', 'R2, Chegutu, Mashonaland West, Zimbabwe, 3.73 km from Chegutu', 'circle', '', '{"city": "Chegutu", "province": "Mashonaland West", "country": "Zimbabwe", "distance": "3.73 km from Chegutu"}'::jsonb),
('Chibi Toll', 'Harare-Beitbridge Highway, Chivi, Masvingo, Zimbabwe, 4.71 km from Ngomahuru', 'circle', '', '{"city": "Chivi", "province": "Masvingo", "country": "Zimbabwe", "distance": "4.71 km from Ngomahuru"}'::jsonb),
('Chibwa Truck Stop', 'Harare-Beitbridge Highway, Masvingo, Zimbabwe, 16.32 km from Ngomahuru', 'circle', '', '{"city": "Masvingo", "country": "Zimbabwe", "distance": "16.32 km from Ngomahuru"}'::jsonb),
('Chipinge District Hospital (+263 27 2901-5)', 'Bhinya Road 2, Chipinge, Manicaland, Zimbabwe, 0.81 km from Chipinge', 'circle', '', '{"city": "Chipinge", "province": "Manicaland", "country": "Zimbabwe", "distance": "0.81 km from Chipinge"}'::jsonb),
('Chiredzi General Hospital (+2632312312421)', 'Lion Drive, Chiredzi, Masvingo, Zimbabwe, 1.29 km from Chiredzi', 'circle', '', '{"city": "Chiredzi", "province": "Masvingo", "country": "Zimbabwe", "distance": "1.29 km from Chiredzi"}'::jsonb),
('Chirumanzu - St Theresa''s Hospital (+263 54 221 315)', 'St Joseph''S Mission, Midlands, Zimbabwe', 'circle', '', '{"province": "Midlands", "country": "Zimbabwe"}'::jsonb),
('Chirundu Zambian Border Post', 'T2, Southern Province, Zambia, 86.06 km from Lusaka', 'polygon', '', '{"province": "Southern Province", "country": "Zambia", "distance": "86.06 km from Lusaka"}'::jsonb),
('Chisumbanje Sleeping Point', 'A10, Chipinge, Manicaland, Zimbabwe, 14.38 km from Zamchiya', 'circle', '', '{"city": "Chipinge", "province": "Manicaland", "country": "Zimbabwe", "distance": "14.38 km from Zamchiya"}'::jsonb),
('Chivhu truck stop', 'A4, Chikomba, Mashonaland East, Zimbabwe, 0.89 km from Chivhu', 'circle', '', '{"city": "Chikomba", "province": "Mashonaland East", "country": "Zimbabwe", "distance": "0.89 km from Chivhu"}'::jsonb),
('CRYSTAL CANDY', 'Burnley Road, Harare, Zimbabwe', 'polygon', '', '{"city": "Harare", "country": "Zimbabwe"}'::jsonb),
('D2 Isando Business Park', 'Gewel St, Isando, Kempton Park 1601, Gauteng, South Africa', 'polygon', '', '{"city": "Kempton Park", "province": "Gauteng", "country": "South Africa", "postal_code": "1601"}'::jsonb),
('Dacher Transhipment', 'Sim Rd 9, Kempton Park Ah, Kempton Park, 1619, Gauteng, South Africa', 'polygon', '', '{"city": "Kempton Park", "province": "Gauteng", "country": "South Africa", "postal_code": "1619"}'::jsonb),
('DAIRYMADE', 'Brakfontein Rd, Louwlardia, Centurion 0157, Gauteng, South Africa', 'polygon', '', '{"city": "Centurion", "province": "Gauteng", "country": "South Africa", "postal_code": "0157"}'::jsonb),
('Doma-Summerhill Farm', 'Lower Doma Road, Makonde, Mashonaland West, Zimbabwe, 12.50 km from Mhangura', 'circle', '', '{"city": "Makonde", "province": "Mashonaland West", "country": "Zimbabwe", "distance": "12.50 km from Mhangura"}'::jsonb),
('Dream pack', 'Long St 9, Saron, 6812, Western Cape, South Africa', 'polygon', '', '{"city": "Saron", "province": "Western Cape", "country": "South Africa", "postal_code": "6812"}'::jsonb),
('Esigodini Toll Plaza', 'Bulawayo-Beitbridge Highway, Umzingwane, Matabeleland South, Zimbabwe, 6.35 km from Esigodini', 'circle', '', '{"city": "Umzingwane", "province": "Matabeleland South", "country": "Zimbabwe", "distance": "6.35 km from Esigodini"}'::jsonb),
('ETG', 'Gleneagles Road, Harare, Zimbabwe', 'polygon', '', '{"city": "Harare", "country": "Zimbabwe"}'::jsonb),
('ETG DEPOT CHIPINGE', 'Main Street Highway, Chipinge, Manicaland, Zimbabwe, 8.27 km from Junction Gate', 'polygon', '', '{"city": "Chipinge", "province": "Manicaland", "country": "Zimbabwe", "distance": "8.27 km from Junction Gate"}'::jsonb),
('EZYTRACK', 'Enterprise Road South, Harare, Zimbabwe', 'polygon', '', '{"city": "Harare", "country": "Zimbabwe"}'::jsonb),
('Fairbridge Tollgate', 'R2, Umguza, Matabeleland North, Zimbabwe, 1.80 km from Cathleen', 'circle', '', '{"city": "Umguza", "province": "Matabeleland North", "country": "Zimbabwe", "distance": "1.80 km from Cathleen"}'::jsonb),
('FARM WISE', 'R44, Klapmuts 7625, Western Cape, South Africa', 'polygon', '', '{"city": "Klapmuts", "province": "Western Cape", "country": "South Africa", "postal_code": "7625"}'::jsonb),
('FBT CPT PORT', 'South Arm Rd, Foreshore, Cape Town 8001, Western Cape, South Africa', 'polygon', '', '{"city": "Cape Town", "province": "Western Cape", "country": "South Africa", "postal_code": "8001"}'::jsonb),
('FEEDMIX', 'R5, Harare, Zimbabwe', 'polygon', '', '{"city": "Harare", "country": "Zimbabwe"}'::jsonb),
('Feedmix Mutare', 'C, Mutare, Manicaland, Zimbabwe, 0.54 km from Mutare', 'circle', '', '{"city": "Mutare", "province": "Manicaland", "country": "Zimbabwe", "distance": "0.54 km from Mutare"}'::jsonb),
('FRESHMARK', 'Olievenhoutbosch Rd, Louwlardia, Centurion 0157, Gauteng, South Africa', 'polygon', '', '{"city": "Centurion", "province": "Gauteng", "country": "South Africa", "postal_code": "0157"}'::jsonb),
('FRESHMARK POLOKWANE', 'Tami, Magna Via Industrial, Polokwane 0699, Limpopo, South Africa', 'polygon', '', '{"city": "Polokwane", "province": "Limpopo", "country": "South Africa", "postal_code": "0699"}'::jsonb),
('FX LOGISTICS', 'Joshua Nkomo Road, Harare, Zimbabwe', 'polygon', '', '{"city": "Harare", "country": "Zimbabwe"}'::jsonb),
('GATEWAY TRUCKSTOP', 'N1, Beit Bridge 0904, Limpopo, South Africa', 'polygon', '', '{"city": "Beit Bridge", "province": "Limpopo", "country": "South Africa", "postal_code": "0904"}'::jsonb),
('Goromonzi Tollgate', 'R5, Goromonzi, Mashonaland East, Zimbabwe, 10.33 km from Ruwa', 'circle', '', '{"city": "Goromonzi", "province": "Mashonaland East", "country": "Zimbabwe", "distance": "10.33 km from Ruwa"}'::jsonb),
('Gwanda Provincial Hospital (+263 84 282 220)', 'A6, Gwanda, Matabeleland South, Zimbabwe, 0.28 km from Gwanda', 'circle', '', '{"city": "Gwanda", "province": "Matabeleland South", "country": "Zimbabwe", "distance": "0.28 km from Gwanda"}'::jsonb),
('Gweru Provincial Hospital (+26354221301)', 'A18, Gweru, Midlands, Zimbabwe, 1.04 km from Gweru', 'circle', '', '{"city": "Gweru", "province": "Midlands", "country": "Zimbabwe", "distance": "1.04 km from Gweru"}'::jsonb),
('Gweru Toll Plaza', 'R2, Gweru, Midlands, Zimbabwe, 14.53 km from Mtapa', 'circle', '', '{"city": "Gweru", "province": "Midlands", "country": "Zimbabwe", "distance": "14.53 km from Mtapa"}'::jsonb),
('Gweru Truck Stop', 'R2, Gweru, Midlands, Zimbabwe, 6.00 km from Mtapa', 'circle', '', '{"city": "Gweru", "province": "Midlands", "country": "Zimbabwe", "distance": "6.00 km from Mtapa"}'::jsonb),
('Harare Central Hospital (+263242621100)', 'Birmingham Road, Harare, Zimbabwe', 'polygon', '', '{"city": "Harare", "country": "Zimbabwe"}'::jsonb),
('HARARE TRUCK STOP', 'Barking Road, Harare, Zimbabwe', 'polygon', '', '{"city": "Harare", "country": "Zimbabwe"}'::jsonb),
('Haulier Logistics', 'Commercial Rd 316, Wadeville, Germiston, 1428, Gauteng, South Africa', 'polygon', '', '{"city": "Germiston", "province": "Gauteng", "country": "South Africa", "postal_code": "1428"}'::jsonb),
('Helderberg Winery', 'Winery Rd, Stellenbosch, Western Cape, South Africa', 'circle', '', '{"city": "Stellenbosch", "province": "Western Cape", "country": "South Africa"}'::jsonb),
('Hexkoelkamers', 'Sir James Avenue, Orchard, Western Cape, South Africa', 'polygon', '', '{"city": "Orchard", "province": "Western Cape", "country": "South Africa"}'::jsonb),
('HFR', 'North Boundary Rd, Sunward Park, Boksburg 1459, Gauteng, South Africa', 'polygon', '', '{"city": "Boksburg", "province": "Gauteng", "country": "South Africa", "postal_code": "1459"}'::jsonb),
('HIDDEN VALLEY', 'Orange Drive, Goromonzi, Mashonaland East, Zimbabwe, 24.35 km from Harare', 'polygon', '', '{"city": "Goromonzi", "province": "Mashonaland East", "country": "Zimbabwe", "distance": "24.35 km from Harare"}'::jsonb),
('Hwange Toll Gate', 'A8, Hwange, Matabeleland North, Zimbabwe, 22.87 km from Chibondo', 'circle', '', '{"city": "Hwange", "province": "Matabeleland North", "country": "Zimbabwe", "distance": "22.87 km from Chibondo"}'::jsonb),
('JHB/HARARE', '', 'line', '', '{}'::jsonb),
('Kadoma Tollgate', 'R2, Kadoma, Mashonaland West, Zimbabwe, 11.11 km from Rimuka', 'circle', '', '{"city": "Kadoma", "province": "Mashonaland West", "country": "Zimbabwe", "distance": "11.11 km from Rimuka"}'::jsonb),
('Karanda Hospital - (+263774082211)', 'Mashonaland Central, Zimbabwe', 'polygon', '', '{"province": "Mashonaland Central", "country": "Zimbabwe"}'::jsonb),
('Koppies farm', 'Chiremba Road, Goromonzi, Mashonaland East, Zimbabwe, 21.02 km from Harare', 'polygon', '', '{"city": "Goromonzi", "province": "Mashonaland East", "country": "Zimbabwe", "distance": "21.02 km from Harare"}'::jsonb),
('Kranskop Toll Plaza', 'N1, Modimolle-Mookgophong, Limpopo, South Africa', 'circle', '', '{"city": "Modimolle-Mookgophong", "province": "Limpopo", "country": "South Africa"}'::jsonb),
('Kwekwe Truck Stop', 'R2, Kwekwe, Midlands, Zimbabwe, 3.74 km from Kwekwe', 'circle', '', '{"city": "Kwekwe", "province": "Midlands", "country": "Zimbabwe", "distance": "3.74 km from Kwekwe"}'::jsonb),
('Lalapansi Tollgate', 'A17, Gweru, Midlands, Zimbabwe, 7.44 km from Indiva', 'circle', '', '{"city": "Gweru", "province": "Midlands", "country": "Zimbabwe", "distance": "7.44 km from Indiva"}'::jsonb),
('LEMBA TRUCK STOP', 'Industria St, Louis Trichardt Ext 5, Louis Trichardt 0920, Limpopo, South Africa', 'polygon', '', '{"city": "Louis Trichardt", "province": "Limpopo", "country": "South Africa", "postal_code": "0920"}'::jsonb),
('Lionsden Farm', 'A1, Makonde, Mashonaland West, Zimbabwe, 17.41 km from Orange Grove', 'circle', '', '{"city": "Makonde", "province": "Mashonaland West", "country": "Zimbabwe", "distance": "17.41 km from Orange Grove"}'::jsonb),
('Lusaka Commercial Cold Store', 'Kafue Road, Lusaka, Zambia', 'polygon', '', '{"city": "Lusaka", "country": "Zambia"}'::jsonb),
('Lymington Tollgate', 'Mutare-Masvingo Highway, Masvingo, Zimbabwe, 17.95 km from Ndanga Business Centre', 'circle', '', '{"city": "Masvingo", "country": "Zimbabwe", "distance": "17.95 km from Ndanga Business Centre"}'::jsonb),
('M & R Marketing (Pty) LTD', 'Gunners Cir 132, Epping Industrial, Cape Town, 7460, Western Cape, South Africa', 'polygon', '', '{"city": "Cape Town", "province": "Western Cape", "country": "South Africa", "postal_code": "7460"}'::jsonb),
('Marondera Provincial Hospital (+263 279 241 041)', '4Th Street, Marondera, Mashonaland East, Zimbabwe, 1.56 km from Marondera', 'circle', '', '{"city": "Marondera", "province": "Mashonaland East", "country": "Zimbabwe", "distance": "1.56 km from Marondera"}'::jsonb),
('Mater Dei Hospital (+263292240000)', 'Burns Drive, Bulawayo, Zimbabwe', 'circle', '', '{"city": "Bulawayo", "country": "Zimbabwe"}'::jsonb),
('Medlog MSC Cold Storage', 'Ithuba Avenue 52, Chesterville, Durban, 4091, Kwazulu Natal, South Africa', 'polygon', '', '{"city": "Durban", "province": "Kwazulu Natal", "country": "South Africa", "postal_code": "4091"}'::jsonb),
('Minx Shipping', 'Houtbaai St 10, Elandshaven, Germiston, 1429, Gauteng, South Africa', 'polygon', '', '{"city": "Germiston", "province": "Gauteng", "country": "South Africa", "postal_code": "1429"}'::jsonb),
('MORGAN CARGO', 'Northern Perimeter Rd, Or Tambo International Airport, Kempton Park 1619, Gauteng, South Africa', 'polygon', '', '{"city": "Kempton Park", "province": "Gauteng", "country": "South Africa", "postal_code": "1619"}'::jsonb),
('Mpfurudzi Toll Plaza', 'P1, Bindura, Mashonaland Central, Zimbabwe, 15.00 km from Village', 'circle', '', '{"city": "Bindura", "province": "Mashonaland Central", "country": "Zimbabwe", "distance": "15.00 km from Village"}'::jsonb),
('Mpilo Central Hospital (+263292212011)', 'Hospital Road, Bulawayo, Zimbabwe', 'circle', '', '{"city": "Bulawayo", "country": "Zimbabwe"}'::jsonb),
('Murehwa District Hospital (+26327822506)', 'A2, Murehwa, Mashonaland East, Zimbabwe, 1.37 km from Murewa', 'circle', '', '{"city": "Murehwa", "province": "Mashonaland East", "country": "Zimbabwe", "distance": "1.37 km from Murewa"}'::jsonb),
('Mushamvura Tollgate', 'Mutare-Masvingo Road, Mutare, Manicaland, Zimbabwe, 13.88 km from Piki Village', 'circle', '', '{"city": "Mutare", "province": "Manicaland", "country": "Zimbabwe", "distance": "13.88 km from Piki Village"}'::jsonb),
('Mutare Provincial Hospital (+263202064321)', 'Jairos Jiri Crescent, Mutare, Manicaland, Zimbabwe, 1.62 km from Chikanga', 'circle', '', '{"city": "Mutare", "province": "Manicaland", "country": "Zimbabwe", "distance": "1.62 km from Chikanga"}'::jsonb),
('Mutare Tollgate', 'R5, Mutasa, Manicaland, Zimbabwe, 6.41 km from Old Mutare', 'circle', '', '{"city": "Mutasa", "province": "Manicaland", "country": "Zimbabwe", "distance": "6.41 km from Old Mutare"}'::jsonb),
('Mvuma Truck Stop', 'A4, Chirumhanzu, Midlands, Zimbabwe, 2.54 km from Mvuma', 'circle', '', '{"city": "Chirumhanzu", "province": "Midlands", "country": "Zimbabwe", "distance": "2.54 km from Mvuma"}'::jsonb),
('Mwenezi Truck Stop', 'Harare-Beitbridge Highway, Mwenezi, Masvingo, Zimbabwe, 0.73 km from Lundi', 'circle', '', '{"city": "Mwenezi", "province": "Masvingo", "country": "Zimbabwe", "distance": "0.73 km from Lundi"}'::jsonb),
('NATIONAL FOODS ASPINDALE', 'Kambuzuma Road, Harare, Zimbabwe', 'polygon', '', '{"city": "Harare", "country": "Zimbabwe"}'::jsonb),
('NATIONAL FOODS BYO', 'Anthony Taylor Avenue, Bulawayo, Zimbabwe', 'circle', '', '{"city": "Bulawayo", "country": "Zimbabwe"}'::jsonb),
('NATIONAL FOODS STIRLING ROAD', 'Stirling Road, Harare, Zimbabwe', 'polygon', '', '{"city": "Harare", "country": "Zimbabwe"}'::jsonb),
('NATURAL AIR', 'Loreley Crescent, Harare, Zimbabwe', 'polygon', '', '{"city": "Harare", "country": "Zimbabwe"}'::jsonb),
('Ndanga Hospital (+263342281)', 'Roy-Buffalo Range Road, Masvingo, Zimbabwe, 1.16 km from Ndanga Business Centre', 'circle', '', '{"city": "Masvingo", "country": "Zimbabwe", "distance": "1.16 km from Ndanga Business Centre"}'::jsonb),
('NESHURO HOSPITAL (+263774660181)', 'Neshuro, Masvingo, Zimbabwe', 'circle', '', '{"city": "Masvingo", "country": "Zimbabwe"}'::jsonb),
('Norton Toll Gate', 'R2, Chegutu, Mashonaland West, Zimbabwe, 5.50 km from Norton', 'circle', '', '{"city": "Chegutu", "province": "Mashonaland West", "country": "Zimbabwe", "distance": "5.50 km from Norton"}'::jsonb),
('NUTRIMASTER', 'Kambuzuma Road, Harare, Zimbabwe', 'polygon', '', '{"city": "Harare", "country": "Zimbabwe"}'::jsonb),
('Nyamagaya', 'A14, Nyanga, Manicaland, Zimbabwe, 2.29 km from Troutbeck', 'circle', '', '{"city": "Nyanga", "province": "Manicaland", "country": "Zimbabwe", "distance": "2.29 km from Troutbeck"}'::jsonb),
('NYAMAPANDA BORDER POST', 'A2, Mudzi, Mashonaland East, Zimbabwe, 0.36 km from Nyamapanda', 'polygon', '', '{"city": "Mudzi", "province": "Mashonaland East", "country": "Zimbabwe", "distance": "0.36 km from Nyamapanda"}'::jsonb),
('Nyl Plaza', 'N1, Mogalakwena, Limpopo, South Africa', 'circle', '', '{"city": "Mogalakwena", "province": "Limpopo", "country": "South Africa"}'::jsonb),
('Plumtree Hospital (+263 83 282 561)', 'A7, Bulilimamangwe, Matabeleland South, Zimbabwe, 0.42 km from Madubes', 'circle', '', '{"city": "Bulilimamangwe", "province": "Matabeleland South", "country": "Zimbabwe", "distance": "0.42 km from Madubes"}'::jsonb),
('POWERSPEED', 'Cripps Road, Harare, Zimbabwe', 'polygon', '', '{"city": "Harare", "country": "Zimbabwe"}'::jsonb),
('Pre Cool Storage DBN', 'Mthoko Mkhize Dr, Elangeni, Cato Ridge 3699, Kwazulu Natal, South Africa', 'polygon', '', '{"city": "Cato Ridge", "province": "Kwazulu Natal", "country": "South Africa", "postal_code": "3699"}'::jsonb),
('Pro Tyre', 'Portland Road, Harare, Zimbabwe', 'circle', '', '{"city": "Harare", "country": "Zimbabwe"}'::jsonb),
('Pumulani Toll Plazas', 'N1, Doornpoort 0186, Gauteng, South Africa', 'circle', '', '{"city": "Doornpoort", "province": "Gauteng", "country": "South Africa", "postal_code": "0186"}'::jsonb),
('QK Meats Coldrooms', 'Niehaus St 16, City Deep, Johannesburg, 2001, Gauteng, South Africa', 'polygon', '', '{"city": "Johannesburg", "province": "Gauteng", "country": "South Africa", "postal_code": "2001"}'::jsonb),
('RAM Petroleum Harare', 'R5, Goromonzi, Mashonaland East, Zimbabwe, 20.85 km from Harare', 'polygon', '', '{"city": "Goromonzi", "province": "Mashonaland East", "country": "Zimbabwe", "distance": "20.85 km from Harare"}'::jsonb),
('RED RANGE', 'Wingrove Road, Bulawayo, Zimbabwe', 'polygon', '', '{"city": "Bulawayo", "country": "Zimbabwe"}'::jsonb),
('REZENDE DEPOT', 'Abercorn Street, Harare, Zimbabwe', 'polygon', '', '{"city": "Harare", "country": "Zimbabwe"}'::jsonb),
('Rusape Tollgate', 'R5, Makoni, Manicaland, Zimbabwe, 14.10 km from Rusape', 'circle', '', '{"city": "Makoni", "province": "Manicaland", "country": "Zimbabwe", "distance": "14.10 km from Rusape"}'::jsonb),
('Rusape Truck Stop - Buffalo Truck Inn', 'R5, Makoni, Manicaland, Zimbabwe, 0.61 km from Rusape', 'circle', '', '{"city": "Makoni", "province": "Manicaland", "country": "Zimbabwe", "distance": "0.61 km from Rusape"}'::jsonb),
('Rutenga truck stop', 'Harare-Beitbridge Highway, Mwenezi, Masvingo, Zimbabwe, 4.91 km from Rutenga', 'polygon', '', '{"city": "Mwenezi", "province": "Masvingo", "country": "Zimbabwe", "distance": "4.91 km from Rutenga"}'::jsonb),
('SA SIDE BB BORDER', 'BORDER POST SA SIDE', 'polygon', '', '{}'::jsonb),
('SCANLINK', 'Barking Road, Harare, Zimbabwe', 'polygon', '', '{"city": "Harare", "country": "Zimbabwe"}'::jsonb),
('Sequence Logistics', 'O Connor Pl 40, Aeroton, 2013, Gauteng, South Africa', 'polygon', '', '{"city": "Aeroton", "province": "Gauteng", "country": "South Africa", "postal_code": "2013"}'::jsonb),
('Shacman SA', 'Dekema Rd, Wadeville, Germiston 1428, Gauteng, South Africa', 'polygon', '', '{"city": "Germiston", "province": "Gauteng", "country": "South Africa", "postal_code": "1428"}'::jsonb),
('Sholiver Farm', 'A1, Zvimba, Mashonaland West, Zimbabwe, 5.82 km from Banket', 'circle', '', '{"city": "Zvimba", "province": "Mashonaland West", "country": "Zimbabwe", "distance": "5.82 km from Banket"}'::jsonb),
('Silver Solutions', 'Sacks Cir 32, Sacks Circle Industrial, Bellville, 7530, Western Cape, South Africa', 'circle', '', '{"city": "Bellville", "province": "Western Cape", "country": "South Africa", "postal_code": "7530"}'::jsonb),
('Skyline Tollgate', 'Simon Mazorodze Road, Harare, Zimbabwe', 'circle', '', '{"city": "Harare", "country": "Zimbabwe"}'::jsonb),
('Sleeping Spot Birchenoage Bridge', 'Mutare-Masvingo Road, Chipinge, Manicaland, Zimbabwe, 1.42 km from Birchenough Bridge', 'polygon', '', '{"city": "Chipinge", "province": "Manicaland", "country": "Zimbabwe", "distance": "1.42 km from Birchenough Bridge"}'::jsonb),
('Sleeping Spot Nyazura', 'R5, Makoni, Manicaland, Zimbabwe, 1.99 km from Nyazura', 'polygon', '', '{"city": "Makoni", "province": "Manicaland", "country": "Zimbabwe", "distance": "1.99 km from Nyazura"}'::jsonb),
('St. Annes Hospital (+263242303360)', 'Oxford Road, Harare, Zimbabwe', 'polygon', '', '{"city": "Harare", "country": "Zimbabwe"}'::jsonb),
('TAMSIDE DEPOT', 'WORKSHOP DIESEL', 'polygon', '', '{}'::jsonb),
('Teralco Logistics', 'Arniston St, Serengeti Golf And Wildlife Estate 1618, Gauteng, South Africa', 'polygon', '', '{"province": "Gauteng", "country": "South Africa", "postal_code": "1618"}'::jsonb),
('TM Warehouse Harare', 'Loreley Close, Harare, Zimbabwe', 'circle', '', '{"city": "Harare", "country": "Zimbabwe"}'::jsonb),
('Trail Star Route Quest', 'Van De Venter St, Cruywagen Park, Germiston 1428, Gauteng, South Africa', 'polygon', '', '{"city": "Germiston", "province": "Gauteng", "country": "South Africa", "postal_code": "1428"}'::jsonb),
('Treetop Toll Plaza', 'R2, Gweru, Midlands, Zimbabwe, 0.87 km from Willoughby', 'circle', '', '{"city": "Gweru", "province": "Midlands", "country": "Zimbabwe", "distance": "0.87 km from Willoughby"}'::jsonb),
('Triangle Collin Saunders Hospital (+263 312 336 253)', 'A10, Chiredzi, Masvingo, Zimbabwe, 1.07 km from Triangle', 'circle', '', '{"city": "Chiredzi", "province": "Masvingo", "country": "Zimbabwe", "distance": "1.07 km from Triangle"}'::jsonb),
('Triangle Toll Plaza (CLOSED)', 'A10, Chiredzi, Masvingo, Zimbabwe, 9.66 km from Triangle', 'circle', '', '{"city": "Chiredzi", "province": "Masvingo", "country": "Zimbabwe", "distance": "9.66 km from Triangle"}'::jsonb),
('TWO A DAY STORAGE', 'R321, Grabouw 7160, Western Cape, South Africa', 'polygon', '', '{"city": "Grabouw", "province": "Western Cape", "country": "South Africa", "postal_code": "7160"}'::jsonb),
('Two Oceans Commercial Cold Store', 'Kuils River Fwy, Marinda Heights, Western Cape, South Africa', 'circle', '', '{"city": "Marinda Heights", "province": "Western Cape", "country": "South Africa"}'::jsonb),
('Umguza Toll Gate', 'A8, Umguza, Matabeleland North, Zimbabwe, 15.01 km from Bulawayo', 'circle', '', '{"city": "Umguza", "province": "Matabeleland North", "country": "Zimbabwe", "distance": "15.01 km from Bulawayo"}'::jsonb),
('Willowton Mutare', 'Mutare-Masvingo Road, Mutare, Manicaland, Zimbabwe, 1.27 km from Sakubva', 'circle', '', '{"city": "Mutare", "province": "Manicaland", "country": "Zimbabwe", "distance": "1.27 km from Sakubva"}'::jsonb),
('Willowtongroup Cape', 'Product St 29, Ndabeni, Cape Town, 7405, Western Cape, South Africa', 'circle', '', '{"city": "Cape Town", "province": "Western Cape", "country": "South Africa", "postal_code": "7405"}'::jsonb);
